title: eXpand WhatsApp Call Center
baseURL: /
params:
  palette: green
  header:
    title: Expand
    logo_img: /images/logo2.png
    has_nav: false
    nav_links:
      - label: Home
        url: /
      - label: Features
        url: /features
      - label: Pricing
        url: /pricing
      - label: Style Guide
        url: /style-guide
      - label: Sign Up
        url: /signup
        primary: true
  footer:
    subscribe_title: Subscribe
    subscribe_content: Stay up to date with our latest developments.
    has_subscribe: false
    social_title: Community
    social_links:
      - label: Twitter
        url: https://twitter.com/
        new_window: true
      - label: Instagram
        url: https://www.instagram.com/
        new_window: true
      - label: LinkedIn
        url: https://www.linkedin.com/
        new_window: true
    tagline: eXpand Omnichannel Customer Journey Software
    logo_img: /images/logo.png
    has_social: false
    content: "&copy; DT Marketing Todos los derechos reservados."
    links:
      - label: Made with ❤
        url: https://www.dtmarketing.com.uy
        new_window: true
    nav_title: eXpand
    nav_links:
      - label: About Us
        url: /about
      - label: Blog
        url: /blog
      - label: Sign Up
        url: signup
      - label: Contact
        url: /contact
    has_nav: false
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
